#!/bin/bash

configPath="$HOME/.config/git_syncer/"
configName="config"

localPath="/storage/emulated/0/"
gitUrl=$1
repoDir=$(basename -s .git "$gitUrl")

gitSync(){
  local gitCmd='git add -A && git commit -m "$(date "+%Y-%m-%d %H:%M:%S")" && git push --set-upstream origin main && git pull'
  local path=$1
  echo "Git Syncing $path"
  eval "cd $path && $gitCmd"
}

gitClone(){
  echo "Git Cloning $gitUrl"
  eval "cd $1 && git clone $gitUrl"
}

setupConfig(){
  echo "Setting up config file $configPath$configName"
  eval "mkdir -p $configPath; touch $configPath$configName"
}

addFileToConfig(){
  local dir=$(dirname "$1")
  if [ -f "$configPath$configName" ]; then
    # Check if the specific content exists in the file
    if [ ! -d $localPath$repoDir ] ; then
      if  ! grep -qF "$1" "$configPath$configName"; then
        echo "Adding Entry $1"
        echo "$1" >> "$configPath$configName"
        gitClone $dir
      else
        gitClone $dir
      fi
    fi
  else
    setupConfig
    echo "Adding Entry $1"
    echo "$1" >> "$configPath$configName"
    gitClone
  fi
}

readConfigFile(){
  echo "Trying to read Config File"
  if [ -f "$configPath$configName" ]; then
    while IFS= read -r line; do
      gitSync "$line"
    done < "$configPath$configName"
  else
    setupConfig
  fi
}


if [ $# -eq 1 ]; then 
  addFileToConfig $localPath$repoDir
  exit
elif [ $# -eq 2 ]; then 
  addFileToConfig $2$repoDir
else
  readConfigFile
fi
